### ISSUE TITLE
Add some non-existent files

### ISSUE THREAD

**Issue by xxs4suk3** [GoldieDevv/Assistant-Bot-Slash-Commands#1]
It is missing some folders such as ./utils and also files such as giveways.js, backup.js, among others

**Comment by GoldieDevv** [comment]
> It is missing some folders such as ./utils and also files such as giveways.js, backup.js, among others

This project is archived as it has been stopped in development

**Comment by xxs4suk3** [comment]
I understand so you can close this proposal :)
